Connection ERROR:
HTTPConnectionPool(host='scratchpd.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x039720D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) @ 08-04-2020 15:50:57
			Connection could not be esteablished
--------------------------------------------------
